Add some pages to allowlist (whitelist) for swiki
miraheze/mw-config pull request #3426
Opened 2020-11-12 22:01 UTC by soratako

Add Main pages for some languages ​​and some special pages to the allow list.

2020-11-13 01:01 UTC, Universal-Omega requested changes

2020-11-13 01:01 UTC, Universal-Omega commented on LocalWiki.php
> +	 $wgWhitelistRead[] = 'メインページ/ja', 'Special:Translate', '特別:翻訳', '特別:履歴', 'メインページ/it', 'メインページ/id', 'メインページ/en-gb', 'メインページ/en-ca', 'メインページ/ko', 'メインページ/zh', 'メインページ/fr', 'メインページ/cy', 'メインページ/eo', '
This won't work with this type of list.

2020-11-13 06:42 UTC, Universal-Omega commented on LocalWiki.php
> +	 $wgWhitelistRead[] = 'メインページ/ja', 'Special:Translate', '特別:翻訳', '特別:履歴', 'メインページ/it', 'メインページ/id', 'メインページ/en-gb', 'メインページ/en-ca', 'メインページ/ko', 'メインページ/zh', 'メインページ/fr', 'メインページ/cy', 'メインページ/eo', '
I still don't think it'll work like that. You're passing an array to an array.

2020-11-14 17:27 UTC, paladox commented on LocalWiki.php
> -	 $wgWhitelistRead[] = 'メインページ/ja';
You would need to do:

$whitelist = [ 'メインページ/ja', 'Special:Translate', '特別:翻訳', '特別:履歴', 'メインページ/it', 'メインページ/id', 'メインページ/en-gb', 'メインページ/en-ca', 'メインページ/ko', 'メインページ/zh', 'メインページ/fr', 'メインページ/cy', 'メインページ/eo', 'メインページ/nl', 'メインページ/lb', 'メインページ/de', 'メインページ/hu', 'メインページ/pt', 'メインページ/ru', 'メインページ/sr', 'メインページ/tt', 'メインページ/th', 'メインページ/hi', 'メインページ/yue', 'Main Page', 'Main page', '特別:携帯機器メニュー', '特別:不正なページ名', 'Project:About', 'Project:Test', 'Test', 'Project:Disclaimers', '特別:アカウント統一管理', '特別:個人設定' ];

$wgWhitelistRead = array_merge( $wgWhitelistRead, $whitelist );

2020-11-17 04:49 UTC, merged