Add MediaModeration extension T5824
miraheze/mw-config pull request #3463
Opened 2020-11-20 16:23 UTC by Reception123

2021-03-14 18:27 UTC, WhatDoYaDoWithADrunkenSailor commented
What will we do with a drunken sailor?
What will we do with a drunken sailor?
What will we do with a drunken sailor?
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Shave his belly with a rusty razor
Shave his belly with a rusty razor
Shave his belly with a rusty razor
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Put him in a long boat 'til he's sober
Put him in a long boat 'til he's sober
Put him in a long boat 'til he's sober
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Stick him in the scupper with a hosepipe on him
Stick him in the scupper with a hosepipe on him
Stick him in the scupper with a hosepipe on him
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Put him in the bed with the captain's daughter
Put him in the bed with the captain's daughter
Put him in the bed with the captain's daughter
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

That's what we do with a drunken sailor
That's what we do with a drunken sailor
That's what we do with a drunken sailor
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'What will we do with a drunken sailor?
What will we do with a drunken sailor?
What will we do with a drunken sailor?
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Shave his belly with a rusty razor
Shave his belly with a rusty razor
Shave his belly with a rusty razor
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Put him in a long boat 'til he's sober
Put him in a long boat 'til he's sober
Put him in a long boat 'til he's sober
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Stick him in the scupper with a hosepipe on him
Stick him in the scupper with a hosepipe on him
Stick him in the scupper with a hosepipe on him
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Put him in the bed with the captain's daughter
Put him in the bed with the captain's daughter
Put him in the bed with the captain's daughter
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

That's what we do with a drunken sailor
That's what we do with a drunken sailor
That's what we do with a drunken sailor
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'What will we do with a drunken sailor?
What will we do with a drunken sailor?
What will we do with a drunken sailor?
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Shave his belly with a rusty razor
Shave his belly with a rusty razor
Shave his belly with a rusty razor
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Put him in a long boat 'til he's sober
Put him in a long boat 'til he's sober
Put him in a long boat 'til he's sober
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Stick him in the scupper with a hosepipe on him
Stick him in the scupper with a hosepipe on him
Stick him in the scupper with a hosepipe on him
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Put him in the bed with the captain's daughter
Put him in the bed with the captain's daughter
Put him in the bed with the captain's daughter
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

That's what we do with a drunken sailor
That's what we do with a drunken sailor
That's what we do with a drunken sailor
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'What will we do with a drunken sailor?
What will we do with a drunken sailor?
What will we do with a drunken sailor?
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Shave his belly with a rusty razor
Shave his belly with a rusty razor
Shave his belly with a rusty razor
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Put him in a long boat 'til he's sober
Put him in a long boat 'til he's sober
Put him in a long boat 'til he's sober
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Stick him in the scupper with a hosepipe on him
Stick him in the scupper with a hosepipe on him
Stick him in the scupper with a hosepipe on him
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Put him in the bed with the captain's daughter
Put him in the bed with the captain's daughter
Put him in the bed with the captain's daughter
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

That's what we do with a drunken sailor
That's what we do with a drunken sailor
That's what we do with a drunken sailor
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

Way hay and up she rises
Way hay and up she rises
Way hay and up she rises
Early in the mornin'

2021-03-23 16:15 UTC, Universal-Omega requested changes

2021-03-23 16:15 UTC, Universal-Omega commented on LocalSettings.php
> +		'default' => 'noreply@miraheze.org',
This would be better as `$wgPasswordSender` I think.

2021-04-30 09:56 UTC, Reception123 commented
No indication that this will be possible anytime soon. Closing.

2021-04-30 09:56 UTC, closed without merging