Convert from travis to GitHub actions
miraheze/mw-config pull request #3554
Opened 2020-12-10 17:51 UTC by MacFan4000

Per https://phabricator.miraheze.org/T6457, travis-ci.org is shutting on the 31st, and travis-ci.com no longer offers a free option. This also adds a PHP 8.0 check.

2020-12-10 17:52 UTC, MacFan4000 commented
A sample check run can be seen at https://github.com/MacFan4000/mw-config/runs/1532386632

2020-12-10 18:20 UTC, RhinosF1 approved these changes

2020-12-12 20:32 UTC, Universal-Omega requested changes

2020-12-15 21:15 UTC, MacFan4000 commented on .github/workflows/workflow.yml
> +        php: ['7.3', '7.4', '8.0']
@Universal-Omega Then why are we testing PHP 7.4 if Miraheze is running PHP 7.3?

2020-12-16 04:12 UTC, Universal-Omega commented on .github/workflows/workflow.yml
> +        php: ['7.3', '7.4', '8.0']
Oh, good question. I do think at least PHP 8.0 should be taken out of here though.

2020-12-20 06:56 UTC, Universal-Omega approved these changes

2020-12-22 17:27 UTC, Universal-Omega commented
Will revert if this does not work good. Merging to test that this will meet our needs.

2020-12-22 17:27 UTC, merged