add wgARENamespaces to ManageWikiNamespaces
miraheze/mw-config pull request #3661
Opened 2021-01-14 22:01 UTC by The-Voidwalker

See https://meta.miraheze.org/w/index.php?title=Community_noticeboard&oldid=156690#Problem_with_ArticleRatings_extension for extra details

2021-01-14 22:57 UTC, dmehus commented
This LGTM, as far as I can tell. Are there any custom configurations for this extension-added variable on existing wikis we'll need to migrate to ManageWiki/namespaces as well?

2021-01-15 00:39 UTC, The-Voidwalker commented
To my knowledge this variable has never been configured before, which is honestly impressive, considering it appears to be required to use the extension. 🙃

2021-01-15 00:42 UTC, dmehus commented
> To my knowledge this variable has never been configured before, which is honestly impressive, considering it appears to be required to use the extension. 🙃

Wow, heh. 👍

2021-01-15 04:09 UTC, Universal-Omega requested changes
This needs to be added to LocalSettings.php also.

2021-01-15 04:13 UTC, Universal-Omega requested changes

2021-01-15 04:13 UTC, Universal-Omega commented on ManageWikiNamespaces.php
> +		'overridedefault' => false,
Should be default to be on on $wgContentNamespaces (https://github.com/wikimedia/mediawiki-extensions-ArticleRatings/blob/5ca30436ade43d27edc9cb2669d2ab8395d06734/ArticleRatingsHooks.php#L10)

2021-01-18 20:15 UTC, The-Voidwalker commented
> This needs to be added to LocalSettings.php also.

I had looked into that, and it seems that none of the other settings in this file are in LS, so I just decided to leave it. Also, to my knowledge any setting in LS.php would be overwritten by the wiki config anyway.

As for setting the default, I'm not actually sure if `overridedefault` (in this context) works the way we'd be expecting it to. I'll take a look.

2021-01-18 20:48 UTC, Universal-Omega requested changes

2021-01-18 20:48 UTC, Universal-Omega commented on ManageWikiNamespaces.php
> +		'overridedefault' => array_fill_keys( $wgContentNamespaces, true ),
Should be overridedefault => default => format I believe

2021-01-18 20:49 UTC, Universal-Omega approved these changes

2021-01-18 22:07 UTC, Universal-Omega requested changes

2021-01-18 22:07 UTC, Universal-Omega commented on ManageWikiNamespaces.php
> +		'overridedefault' => array_fill_keys( $wgContentNamespaces, true ),
will need to have the `'default' => false,` value also

2021-01-18 22:17 UTC, Universal-Omega approved these changes

2021-01-18 22:37 UTC, merged