Update with missing default Kartographer params
miraheze/mw-config pull request #4490
Opened 2022-03-08 11:16 UTC by ugochimobi

please review and merge appropriately

2022-03-09 18:04 UTC, ugochimobi commented
Oh, I never thought of that

On Wed, Mar 9, 2022, 17:35 RhinosF1 ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In LocalSettings.php
> <https://github.com/miraheze/mw-config/pull/4490#discussion_r822849925>:
>
> >  	],
>  	'wgKartographerStyles' => [
>  		'default' => [],
> +		'gratispaideiawiki' => [
> +			'osm-intl',
> +			'osm',
> +		],
> +		'gratisdatawiki' => [
> +			'osm-intl',
> +			'osm',
> +		],
> +	],
> +	'wgKartographerEnableMapFrame' => [
>
> these are obsolete and currently set by default
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/miraheze/mw-config/pull/4490#pullrequestreview-904651135>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATP5IZJKMUDS52OS2PUITJ3U7DHMRANCNFSM5QGBMNKA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-09 18:05 UTC, ugochimobi commented
Although, I doubt it

2022-03-09 18:07 UTC, ugochimobi commented on LocalSettings.php
> +	'wgKartographerEnableMapFrame' => [
Actually the wgKartographerSrcsetScales is not defautly set

2022-03-09 18:08 UTC, ugochimobi commented on LocalSettings.php
> +	'wgKartographerEnableMapFrame' => [
Most of them aren't default configs

2022-03-09 18:09 UTC, RhinosF1 commented
They are according to the docs

2022-03-09 18:12 UTC, ugochimobi commented
The docs on mediawiki?

2022-03-09 18:31 UTC, RhinosF1 commented
Yes

2022-03-10 06:57 UTC, Reception123 requested changes

2022-03-10 06:57 UTC, Reception123 commented on LocalSettings.php
> +		'gratispaideiawiki' => [1.3, 1.5, 2, 2.6, 3],
please use different lines like [
1.3,
1.5,

2022-03-10 07:08 UTC, ugochimobi commented on LocalSettings.php
> +		'gratispaideiawiki' => [1.3, 1.5, 2, 2.6, 3],
Done

2022-03-10 08:37 UTC, ugochimobi commented
Seems these configurations are defaulting from extension.json

2022-03-10 08:37 UTC, closed without merging