PropertySuggester/APH configs for GD/GP
miraheze/mw-config pull request #4503
Opened 2022-03-11 14:28 UTC by ugochimobi

2022-03-16 06:45 UTC, Reception123 requested changes
wgPropertySuggesterClassifyingPropertyIds and wgPropertySuggesterInitialSuggestions were added in ManageWiki in #4446.

2022-03-16 10:54 UTC, ugochimobi commented
Yeah @Reception123, I intentionally wants it it be set on LocalSettings.php

On Wed, Mar 16, 2022 at 7:45 AM Reception123 ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> wgPropertySuggesterClassifyingPropertyIds and
> wgPropertySuggesterInitialSuggestions were added in ManageWiki in #4446
> <https://github.com/miraheze/mw-config/pull/4446>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/miraheze/mw-config/pull/4503#pullrequestreview-911158350>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATP5IZPA26UXHXDTWQYAT3LVAF7PPANCNFSM5QPY3PEA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-17 05:52 UTC, Reception123 approved these changes

2022-03-17 05:52 UTC, merged

2022-03-17 05:53 UTC, Reception123 commented
Accidentally merged. If they are able to be set in ManageWiki they can't be in LS. Why can't you with MW?