necessary wikibase settings for gp/gd
miraheze/mw-config pull request #4508
Opened 2022-03-14 07:39 UTC by ugochimobi

2022-03-19 01:24 UTC, Universal-Omega requested changes

2022-03-19 01:24 UTC, Universal-Omega commented on Wikibase.php
> +	$wgWBRepoSettings['pagePropertiesRdf'] = [
This is unnecessary, seems to be equal to the default.

2022-03-19 12:51 UTC, ugochimobi commented
Fixed that now

2022-03-27 17:09 UTC, Universal-Omega approved these changes

2022-03-27 21:09 UTC, merged