Popups config for gratispaideiawiki
miraheze/mw-config pull request #4509
Opened 2022-03-14 08:43 UTC by ugochimobi

2022-03-16 06:47 UTC, Reception123 commented
You forgot to add the default for all the settings you are adding.

2022-03-17 05:55 UTC, Reception123 requested changes

2022-03-17 05:55 UTC, Reception123 commented on LocalSettings.php
> +                'default' => '',
https://github.com/wikimedia/mediawiki-extensions-Popups/blob/master/extension.json#L67

2022-03-17 05:55 UTC, Reception123 commented on LocalSettings.php
> +                'default' => '',
https://github.com/wikimedia/mediawiki-extensions-Popups/blob/master/extension.json#L71

2022-03-17 05:55 UTC, Reception123 commented on LocalSettings.php
> +                'default' => null,
Already the default setting; no need for this (https://github.com/wikimedia/mediawiki-extensions-Popups/blob/master/extension.json#L63)

2022-03-17 07:47 UTC, ugochimobi commented
@Reception123 This should be done now

2022-03-17 12:26 UTC, Reception123 commented
@ugochimobi Sorry you keep getting confused about this. Let me try to explain again.

The default value is the one that exists in the extensions extension.json, and unless it is changed that is what it will be for all Miraheze wikis. If a wiki wants to have a different value than the one that is default that will have to be added, but the default value will also have to be.

So you need to do both the default (as it's shown in extension.json) AND the value you need for your wiki.

2022-03-17 13:07 UTC, Reception123 commented
no, just like you did https://github.com/miraheze/mw-config/commit/ab883efb06146b2a9d1c28fa187f1acf6e4cec8e

2022-03-17 13:12 UTC, ugochimobi commented
okay, but if want I want is also the default, then I should add just default right?

2022-03-17 13:37 UTC, Reception123 commented
> okay, but if want I want is also the default, then I should add just default right?

No, because the default already applies because of extension.json, it doesn't need to be added separately to LS

2022-03-17 13:42 UTC, ugochimobi commented
Ah, I don't know why I am doubting that, because there are so many things that are supposed to be happening (apart from this PR) which aren't and it's causing me to doubt

2022-03-19 01:16 UTC, Universal-Omega requested changes
+this is pointless, we are adding configs, setting only defaults that would already be done by the extension.

2022-03-19 01:16 UTC, Universal-Omega commented on LocalSettings.php
> +                'default' => 1,
This should be a string.

2022-03-19 13:09 UTC, closed without merging