Update Wikibase.php with propertyOrderUrl and dataRightsText
miraheze/mw-config pull request #4583
Opened 2022-04-14 10:05 UTC by ugochimobi

2022-04-14 19:47 UTC, Universal-Omega requested changes

2022-04-14 19:47 UTC, Universal-Omega commented on Wikibase.php
> +	$wgWBClientSettings['propertyOrderUrl'] = 'https://gratisdata.miraheze.org/wiki/MediaWiki:Wikibase-SortedProperties?action=raw&sp_ver=1';
I thought the link should point to the repo but be configured on the client?

2022-04-15 02:34 UTC, ugochimobi commented
That's exactly how it is currently.

On Thu, Apr 14, 2022, 20:47 Universal Omega ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In Wikibase.php
> <https://github.com/miraheze/mw-config/pull/4583#discussion_r850755381>:
>
> > @@ -233,6 +234,7 @@
>  		'url' => 'https://static.miraheze.org/commonswiki/a/a4/GDechoIcon.svg',
>  	];
>  	$wgWBClientSettings['repoSiteId'] = 'gratisdatawiki';
> +	$wgWBClientSettings['propertyOrderUrl'] = 'https://gratisdata.miraheze.org/wiki/MediaWiki:Wikibase-SortedProperties?action=raw&sp_ver=1';
>
> I thought the link should point to the repo but be configured on the
> client?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/miraheze/mw-config/pull/4583#pullrequestreview-942729293>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATP5IZJ5JCHDAP3PZGG5DOTVFBY6RANCNFSM5TNJHVAA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-04-15 02:55 UTC, Universal-Omega approved these changes

2022-04-15 02:55 UTC, merged