Add essential special pages to `*`
miraheze/mw-config pull request #4631
Opened 2022-04-24 15:35 UTC by dmehus

Per [[ https://meta.miraheze.org/w/index.php?title=Stewards%27_noticeboard&diff=next&oldid=246492&diffmode=source#I_have_a_question | SN request ]]. This has created the scenario where these rights where these rights were blacklisted from being removed from `*`, but on wikis that already removed them, they cannot be re-added, by local bureaucrats or Stewards. This was an unfortunate oversight as these _should've_ been made default `*` rights, locked down from being removed in ManageWiki

2022-04-24 15:42 UTC, Universal-Omega requested changes

2022-04-24 15:42 UTC, Universal-Omega commented on LocalSettings.php
> +				'editmyoptions',
This and below: => true needed.

2022-04-24 15:48 UTC, dmehus commented on LocalSettings.php
> +				'editmyoptions',
Oh, my bad! Totally missed that.

2022-04-24 16:09 UTC, Universal-Omega approved these changes

2022-04-24 16:10 UTC, Universal-Omega requested changes

2022-04-24 16:10 UTC, Universal-Omega commented on LocalSettings.php
> +				'editmyprivateinfo' => true,
This is already present above.

2022-04-25 02:45 UTC, dmehus commented on LocalSettings.php
> +				'editmyprivateinfo' => true,
Done

2022-04-25 02:46 UTC, Universal-Omega approved these changes

2022-04-25 02:46 UTC, merged