Wikibase configurations for gpcommonswiki
miraheze/mw-config pull request #4640
Opened 2022-04-26 22:42 UTC by ugochimobi

2022-04-27 05:40 UTC, Universal-Omega requested changes

2022-04-27 05:40 UTC, Universal-Omega commented on Wikibase.php
> +		// Some well-known properties' IDs which are used to format references
Tabbing

2022-04-28 16:17 UTC, ugochimobi commented
@Universal-Omega Fixed

2022-04-29 02:49 UTC, Universal-Omega commented
Conflicts

2022-04-29 08:35 UTC, ugochimobi commented
Done

2022-04-29 08:36 UTC, Universal-Omega approved these changes

2022-04-29 08:37 UTC, merged