T9328: set base of wgMinervaShowCategories to true for criticalrolewiki
miraheze/mw-config pull request #4728
Opened 2022-06-03 16:56 UTC by ugochimobi

defaults confirmed from skin.json

2022-06-15 19:41 UTC, Universal-Omega requested changes

2022-06-15 19:41 UTC, Universal-Omega commented on LocalSettings.php
> +			'amc' => false,
This is enabled by default.

2022-06-15 19:41 UTC, Universal-Omega commented on LocalSettings.php
> +			'amc' => false,
Should also be true for override unless requested otherwise.

2022-06-18 05:07 UTC, Reception123 approved these changes

2022-06-18 05:07 UTC, merged