Add support for loading images from swift backend
miraheze/mw-config pull request #4913
Opened 2022-10-04 14:55 UTC by paladox

Using config setting

2022-10-04 19:32 UTC, Universal-Omega commented
Shouldn't we use FileBackendMultiWrite for the swift migration to write to both for now? The purpose of that states "useful for transitioning from one backend to another" which is exactly what we are doing here.

2022-10-05 14:16 UTC, paladox commented
> Shouldn't we use FileBackendMultiWrite for the swift migration to write to both for now? The purpose of that states "useful for transitioning from one backend to another" which is exactly what we are doing here.

No, as we're migrating in stages. We aren't doing it in one big swoop.

2022-10-05 17:08 UTC, Universal-Omega requested changes
There is also some minor code quality things I could point out, but probably not 100% needed right now and pretty minor for the most part.

2022-10-05 17:11 UTC, Universal-Omega commented on FileBackend.php
> +	'zones' => [
Maybe not though I can't remember if I set it to go to dbname/ImportDump or just /ImportDump when making that...

2022-10-06 00:03 UTC, paladox commented on GlobalSettings.php
> +if ( $wi->isExtensionActive( 'score' ) ) {
Thanks, done.

2022-10-06 00:03 UTC, paladox commented on GlobalSettings.php
> +if ( $wi->isExtensionActive( 'timeline' ) ) {
Thanks, done.

2022-10-06 00:22 UTC, paladox commented on FileBackend.php
> +	'zones' => [
Thanks, done.

2022-10-06 02:01 UTC, Universal-Omega approved these changes
Looks good to me now, provided it actually works, since I only reviewed the code here I can't guarantee anything else.

2022-10-07 19:49 UTC, merged