make gpcommonswiki the wgGlobalUsageDatabase for gp wikis
miraheze/mw-config pull request #5066
Opened 2023-01-12 16:11 UTC by ugochimobi

2023-01-21 09:15 UTC, ugochimobi commented
@Universal-Omega Take a look at this too, please.

2023-01-22 23:40 UTC, Universal-Omega requested changes

2023-01-22 23:40 UTC, Universal-Omega commented on LocalSettings.php
> +		'default' => 'commonswiki',
this is defaulted to false.

2023-01-23 19:32 UTC, Universal-Omega approved these changes

2023-01-23 19:32 UTC, merged