Update LocalSettings.php
miraheze/mw-config pull request #5290
Opened 2023-08-01 18:45 UTC by robkam

Add class extiw for [extension LinkTarget](https://www.mediawiki.org/wiki/Extension:LinkTarget) on sdiywiki, scruffywiki and simpleelectronicswiki as per [T11084](https://phabricator.miraheze.org/T11084), [T11101](https://phabricator.miraheze.org/T11101) and [T11102](https://phabricator.miraheze.org/T11102).

Trying to get target="_blank" on interwiki links.

2023-09-11 13:16 UTC, paladox commented
Can the title be updated?

2023-09-12 15:58 UTC, R4356th requested changes

2023-09-12 15:58 UTC, R4356th commented on LocalSettings.php
> +		'sdiywiki' => '_blank' => [ 'extiw' ],
Add a `[` sign in front of `'_blank'` and a `]` sign after `'extiw' ]` (but before the comma!). Repeat this for the other lines as well.

2023-09-19 21:05 UTC, closed without merging

2023-09-20 19:46 UTC, robkam commented
oops, don't know why I deleted this