Add PageLanguage and PerPageLanguage to MW extensions
miraheze/mw-config pull request #5562
Opened 2024-05-15 02:54 UTC by brandon-wm

2024-05-15 04:16 UTC, clarfonthey commented
Definitely looks fine for PageLanguage (WMF supported) but my only concern with PerPageLanguage is that we prefer updating to the latest MW version when it comes out, and they might lag behind in support.

2024-05-16 16:48 UTC, Universal-Omega requested changes

2024-05-16 16:48 UTC, Universal-Omega commented on ManageWikiExtensions.php
> +		'requires' => [],
```suggestion
		'requires' => [],
		'install' => [
			'settings' => [
				'wgPageLanguageUseDB' => true,
			],
		],
```

2024-05-16 16:55 UTC, Universal-Omega requested changes
'name' must match the name in extension.json

2024-05-16 16:55 UTC, Universal-Omega commented on ManageWikiExtensions.php
> +		'name' => 'PageLanguage',
```suggestion
		'name' => 'Page Language',
```

2024-05-16 17:03 UTC, Universal-Omega approved these changes

2024-05-16 17:03 UTC, merged