T12447: Add GoogleForms
miraheze/mw-config pull request #5633
Opened 2024-08-09 18:42 UTC by AverageHelper

If I understand right, this and https://github.com/miraheze/mediawiki-repos/pull/30 together should add the GoogleForms extension to `Special:ManageWiki/extensions`.

2024-08-10 08:23 UTC, BlankEclair requested changes

2024-08-10 08:23 UTC, BlankEclair commented on ManageWikiExtensions.php
> +		'name' => 'CustomSearchProfiles',
Probably should be GoogleForms

2024-08-10 08:23 UTC, BlankEclair commented on ManageWikiExtensions.php
> +		'section' => 'other',
Probably better goes in "parserhooks"

2024-08-11 00:39 UTC, AverageHelper commented on ManageWikiExtensions.php
> +		'name' => 'CustomSearchProfiles',
Whoops 😅

2024-08-11 00:41 UTC, BlankEclair approved these changes

2024-09-09 14:44 UTC, Reception123 approved these changes

2024-09-09 14:44 UTC, merged