[WIP, Need help] Update UploadWizard settings for kagagawiki
miraheze/mw-config pull request #5643
Opened 2024-08-22 07:58 UTC by hurohukidaikon

We have some problems on UploadWizard.

### 1. Complex choices
We want to use more simple choices.

We are expecting to these choices.
![スクリーンショット 2024-08-22 16 47 41](https://github.com/user-attachments/assets/edac463c-562a-4cb0-adc4-f5327ba680a9)
![スクリーンショット 2024-08-22 16 47 50](https://github.com/user-attachments/assets/e63a9601-af60-4d6b-ae61-b3fce6437d91)
These are our old version wiki before transporting in Miraheze.

So, we want to disable some choices if we can.
![スクリーンショット 2024-08-22 16 43 04](https://github.com/user-attachments/assets/32e86d5c-018e-41e0-8085-9a22f2b971cb)
![スクリーンショット 2024-08-22 16 44 37](https://github.com/user-attachments/assets/d321afab-5f13-4370-9ed1-bcb2fe90076e)

### 2. System messages are not working.

I created some message pages like below, but these seems to be not working.
- https://kagaga.jp/wiki/MediaWiki:Wm-license-cc-free
- https://kagaga.jp/wiki/MediaWiki:Wm-license-cc-free-to-share-header
- https://kagaga.jp/wiki/MediaWiki:Wm-license-cc-free-to-share-text
I know this is template error, but I couldn't find any solutions so please let me know them.
This template was imported from Wikipedia and not any changes.

https://kagaga.jp/wiki/テンプレート:Cc-by-sa-4.0
![スクリーンショット 2024-08-22 16 40 45](https://github.com/user-attachments/assets/f8bc0b80-5d04-492e-a05b-2c675d2e8d1d)

2024-08-22 09:02 UTC, songnguxyz commented
For the messages, check out my task for a solution: https://issue-tracker.miraheze.org/T12267#248037
I would like to know more about what you are trying to achieve with it, consider contacting me in Discord at `@songngu.xyz` and I will get back to you later!

2024-08-23 00:51 UTC, hurohukidaikon commented
@songnguxyz
Thank you for your reply.
My old wiki (ver. 1.38.2) has the Upload Wizard (ver. 1.5.0), and my custom license is working on it, but current version isn't.
Also license choices are more simple on my old wiki.
I want to achieve adding custom license, and simplify license choices like my old wiki.

2024-08-27 14:44 UTC, hurohukidaikon commented
Problem 2 is works well now.
Maybe the cause is time lug.
When I set the messages few days ago, it is not worked.
But now it is working.
I guess it related with maintenance script and updating DB.
![スクリーンショット 2024-08-27 23 34 01](https://github.com/user-attachments/assets/3b8fa58b-4d29-42cf-919b-89024ea53d6b)

Problem 1 is not critical for us.
So, I want to merge this PR.

2024-08-27 15:06 UTC, hurohukidaikon commented
> I guess it related with maintenance script and updating DB.

Now I tested below, maybe it is correct.

1. Disable UploadWizard
2. Wait few minutes (Check Special:Uploadwizard page. if it is not found, the time to go to next step.)
3. Enable UploadWizard (Run script and update DB)
4. The messages not worked in UploadWizard are working!

2024-08-30 02:31 UTC, hurohukidaikon commented
@Universal-Omega 
Please review it.

2024-08-30 10:56 UTC, songnguxyz approved these changes
Looks cool to me

2024-08-31 15:32 UTC, songnguxyz commented
@hurohukidaikon Just for your information, the breaking change we mentioned was https://phabricator.wikimedia.org/T347749, which mentions a new flow of choosing licenses and confirming that they abide by copyright policy, which is probably too much for non-WMF sites like us.

2024-09-01 02:03 UTC, hurohukidaikon commented
@songnguxyz Thanks for the information!
Yes, too much. In the future, I wish it provided some options for simplifying.

2024-09-09 01:32 UTC, Universal-Omega requested changes

2024-09-09 01:32 UTC, Universal-Omega commented on LocalWiki.php
> +					'availableLanguages' => $uwCcAvailableLanguages
Variable is not set

2024-09-09 04:32 UTC, Universal-Omega approved these changes

2024-09-09 04:32 UTC, merged